# Generated by Django 3.0.5 on 2020-04-27 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('released', models.DateTimeField(blank=True, null=True)),
                ('added', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
        ),
    ]
