# Generated by Django 3.0.5 on 2020-04-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_music_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='author',
            field=models.CharField(default='mihir', max_length=100),
            preserve_default=False,
        ),
    ]
